### PR TITLE
Fixed incorrect RestClient method getAlarms

### LINKED ISSUE #4396: [Bug] java rest sdk getAlarms exception
**Describe the bug**
I traced the source code because the getTimeUrlParams method is called in the getAlarms method when jointing url of getAlarms, but this method adds the Limit parameter and in fact there is no limit in the passed parameter, and I also check the server source code of getAlarms, which does not handle this limit parameter

getAlarms -> getTimeUrlParams
```
public PageData<AlarmInfo> getAlarms(EntityId entityId, AlarmSearchStatus searchStatus, AlarmStatus status, TimePageLink pageLink, Boolean fetchOriginator) {
        Map<String, String> params = new HashMap<>();
        params.put("entityType", entityId.getEntityType().name());
        params.put("entityId", entityId.getId().toString());
        params.put("searchStatus", searchStatus == null ? null : searchStatus.name());
        params.put("status", status == null ? null : status.name());
        params.put("fetchOriginator", String.valueOf(fetchOriginator));
        addTimePageLinkToParam(params, pageLink);

        return restTemplate.exchange(
                baseURL + "/api/alarm/{entityType}/{entityId}?searchStatus={searchStatus}&status={status}&fetchOriginator={fetchOriginator}&" + getTimeUrlParams(pageLink),
                HttpMethod.GET,
                HttpEntity.EMPTY,
                new ParameterizedTypeReference<PageData<AlarmInfo>>() {
                },
                params).getBody();
    }
```

getTimeUrlParams -> `String urlParams = "limit={limit}&ascOrder={ascOrder}"`
```
private String getTimeUrlParams(TimePageLink pageLink) {
        String urlParams = "limit={limit}&ascOrder={ascOrder}";
        if (pageLink.getStartTime() != null) {
            urlParams += "&startTime={startTime}";
        }
        if (pageLink.getEndTime() != null) {
            urlParams += "&endTime={endTime}";
        }
        return urlParams;
    }
```

**Your Server Environment**
ThingsBoard Version 3.2.1
OS Name and Version CentOS 8

**Your Client Environment**
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

```
<dependency>
            <groupId>org.thingsboard</groupId>
            <artifactId>rest-client</artifactId>
            <version>3.2.0</version>
</dependency>
```

### PR DESCRIPTION
**Pull request by AndrewVolosytnykhThingsboard**
Fixed #4396

### CODE REVIEW

**Review by YevhenBondarenko — APPROVED** [review]

File: rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java [hunk 1]
```diff
@@ -305,17 +306,28 @@ public void clearAlarm(AlarmId alarmId) {
...
+            params.put("searchStatus", searchStatus.name());
+            urlSecondPart += "searchStatus={searchStatus}&";
+        }
+        if(status != null) {
+            params.put("status", status.name());
+            urlSecondPart += "status={status}&";
+        }
         params.put("fetchOriginator", String.valueOf(fetchOriginator));
+        if(offset != null) {
+            params.put("offset", offset.toString());
```
Comment (ashvayka) [inline rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java:324]: Please remove this field from the call and remove 
```java
private UUID idOffset;
```
from org.thingsboard.server.common.data.alarm.AlarmQuery since it is not used (and from controller)

File: rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java [hunk 2]
```diff
@@ -2841,7 +2853,7 @@ public void syncEdge(EdgeId edgeId) {
     }
 
     private String getTimeUrlParams(TimePageLink pageLink) {
-        String urlParams = "limit={limit}&ascOrder={ascOrder}";
+        String urlParams = getUrlParams(pageLink);
```
Comment (ashvayka) [inline rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java:2856]: nice catch!

File: rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java [hunk 3]
```diff
@@ -306,16 +305,24 @@ public void clearAlarm(AlarmId alarmId) {
     }
 
     public PageData<AlarmInfo> getAlarms(EntityId entityId, AlarmSearchStatus searchStatus, AlarmStatus status, TimePageLink pageLink, Boolean fetchOriginator) {
+        String urlSecondPart = "/api/alarm/{entityType}/{entityId}?fetchOriginator={fetchOriginator}&";
```
Comment (ashvayka) [inline rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java:308]: Please remove the '&' from the end of this part. Use 

```java
        if(searchStatus != null) {
            params.put("searchStatus", searchStatus.name());
            urlSecondPart += "&searchStatus={searchStatus}";
        }
```

instead of 

```java
        if(searchStatus != null) {
            params.put("searchStatus", searchStatus.name());
            urlSecondPart += "searchStatus={searchStatus}&";
        }
```
